{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if and .Values.manifests.deployment_moncheck .Values.deployment.ceph }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.static.moncheck }}

{{- $serviceAccountName := "ceph-mon-check"}}
{{ tuple $envAll $dependencies $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ceph-mon-check
spec:
  replicas: {{ .Values.pod.replicas.mon_check }}
  template:
    metadata:
      labels:
{{ tuple $envAll "ceph" "moncheck" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      affinity:
{{ tuple $envAll "ceph" "moncheck" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.mon.node_selector_key }}: {{ .Values.labels.mon.node_selector_value }}
      initContainers:
{{ tuple $envAll $dependencies list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: ceph-init-dirs
          image: {{ .Values.images.tags.ceph_daemon }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - /tmp/init-dirs.sh
          env:
            - name: CLUSTER
              value: "ceph"
          volumeMounts:
            - name: ceph-bin
              mountPath: /tmp/init-dirs.sh
              subPath: init-dirs.sh
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
      containers:
        - name: ceph-mon
          image: {{ .Values.images.tags.ceph_daemon }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.moncheck | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: CLUSTER
              value: "ceph"
            - name: K8S_HOST_NETWORK
              value: "1"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          command:
            - /tmp/moncheck-start.sh
          ports:
            - containerPort: 6789
          volumeMounts:
            - name: ceph-bin
              mountPath: /tmp/moncheck-start.sh
              subPath: moncheck-start.sh
              readOnly: true
            - name: ceph-bin
              mountPath: /tmp/moncheck-reap-zombies.py
              subPath: moncheck-reap-zombies.py
              readOnly: true
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
            - name: ceph-mon-keyring
              mountPath: /etc/ceph/ceph.mon.keyring
              subPath: ceph.mon.keyring
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: pod-run
              mountPath: /run
              readOnly: false
      volumes:
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: ceph-bin
          configMap:
            name: ceph-bin
            defaultMode: 0555
        - name: pod-var-lib-ceph
          emptyDir: {}
        - name: pod-run
          emptyDir:
            medium: "Memory"
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
        - name: ceph-mon-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mon }}
{{- end }}
